version: "3.8"

services:
  app1:
    build: ./app 
    ports:
     - 5000
  app2: 
    build: ./app
    ports:
      - 5000
  app3:
    build: ./app
    ports:
      - 5000  
  nginx:
    image: nginx
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - app1
      - app2
      - app3

   